name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - run: |
          pnpm i --frozen-lockfile
          pnpm run build
      - name: Set Firebase CLI Experiments
        run: echo "FIREBASE_CLI_EXPERIMENTS=webframeworks" >> $GITHUB_ENV
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DANIELAROBLESABOGADA }}
          channelId: live
          projectId: danielaroblesabogada
